import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import Navbar from './components/navbar';
import SocialIcons from './components/social-icons';

const robotoSlab = Roboto_Slab({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>
        <div className="px-12 py-6 md:px-96 md:py-24 flex flex-col gap-8">
          <Navbar />
          {children}
          <SocialIcons />
        </div>
      </body>
    </html>
  );
}
